### PR TITLE
Bug/build config syntax

### PR DESCRIPTION
**Pull request by israelias**
*Description of changes:*

This PR addresses naming an unnamed var in `vue.config.js` that was blocking `npm run build-dist` in `/lex-web-ui`. It also brings `webpack.config.js` into v5 syntax in order to `npm run dev` without the following schema error on `devServer`:

```shell
❯ npm run dev

> aws-lex-web-ui@0.20.0 dev
> webpack-dev-server --mode development  --hot

[webpack-cli] Invalid options object. Dev Server has been initialized using an options object that does not match the API schema.
 - options has an unknown property 'stats'. These properties are valid:
   object { allowedHosts?, bonjour?, client?, compress?, devMiddleware?, headers?, historyApiFallback?, host?, hot?, http2?, https?, ipc?, liveReload?, magicHtml?, onAfterSetupMiddleware?, onBeforeSetupMiddleware?, onListening?, open?, port?, proxy?, server?, setupExitSignals?, setupMiddlewares?, static?, watchFiles?, webSocketServer? }
~/aws-lex-web-ui on master !23 ❯        
```

*Refs:*
- _[webpack@5#devServer](https://webpack.js.org/configuration/dev-server/)_

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by atjohns** [comment]
First, thank you for submitting this PR.

It looks like some changes are in here that are not part of the purpose of the PR. Also, I'd be interested to know if Release 0.20.0 fixed these issues since that release does bring the build up to webpack5.

**Comment by israelias** [comment]
Hey @atjohns I synced our team's fork to 0.20.0 and pushed this PR there.

**Comment by israelias** [comment]
@atjohns Apologies not sure how I inadvertently reeled those four commits into this PR. I'll fix to follow protocol, let me know if it's a go

**Comment by atjohns** [comment]
> Hey @atjohns I synced our team's fork to 0.20.0 and pushed this PR there.

Yes I forgot to sync our distribution build back to development, so its probably my fault. There's still a lot of noise in the PR for some reason. Its still picking up the Oct 4/11th pushes and not just your commits. Looking at it more.

**Comment by atjohns** [comment]
@israelias worse comes to worse if you need to do a new PR that's fine. I do want to pull in these changes though

**Comment by israelias** [comment]
@atjohns Copy lemme close this

**Pull request closed without merging**
