### PR TITLE
Fix/config: bundler and loader syntax variety

### PR DESCRIPTION
**Pull request by israelias**
*Description of changes:*

This PR picks up some red errors when running  `npm run build` at root, `npm run build-dist` at child, and `npm run dev` at either, which exposed the anomalies via stack trace in debug/dev mode.

1.  Define `isProd`  to correctly map `env`

```sh
> aws-lex-web-ui@0.20.2 build-dev
> webpack --mode development

env { WEBPACK_BUNDLE: true, WEBPACK_BUILD: true }
(env.production === true) false
env.production undefined
```

2.  Refactor/fix [copy-webpack-plugin](https://webpack.js.org/plugins/copy-webpack-plugin/) v5 signature in`webpack.config.js` Note: `optimization.minimize: false` removes License.txt outputs [`file].LICENSE.txt[query]`](https://webpack.js.org/plugins/terser-webpack-plugin/#filename) without [plugging Terser](https://github.com/webpack/webpack/issues/12506).

3.  Fix array method in copy plugin at `vue.config.js`

4.  Fix incorrect object paths to `parentOrigin` through `ui.parentOrigin`  in `iframeComponentLoader` previously hanging loosely at `config` during the loader's config/merge options variety. (Consequence to options passed at `load` not fully tested). An undefined `tokens` variable was also moved to the outer scope.

<div align="center">Screen Shot 2023-12-12 at 9 58 27 PM</div>

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by atjohns** [comment]
Thanks for the PR, I will take a look shortly

**Comment by israelias** [comment]
Env/Node:

```shell
nvm use 16 
>>> v16.20.2
```

**Comment by atjohns** [comment]
@israelias is Node 16+ required now for the build, do we need to update the package.json as well as part of this?

**Comment by israelias** [comment]
@atjohns not necessarily but it's the engine we've been running with

we started last year at `16.3.0` to accommodate a legacy peer-dep variety (November 2022) and randomly set to latest v16  (16.20.2, npm8.19.4) this summer and haven't really looked back.

stayed in range set in package.json. but let me know if you encounter a strict scenario...

**Comment by israelias** [comment]
See if you are able to run `build` without this error at CopyPlugin. This was the culprit for us, and couldn't fully upgrade to `0.2.*`  with the right web-pack/cli combo as a result. (Until this fix )

```shell
[webpack-cli] [Error: EACCES: permission denied, mkdir '/Users/lex-web-ui'] {
  errno: -13,
  code: 'EACCES',
  syscall: 'mkdir',
  path: '/Users/lex-web-ui'
}
```

**Comment by atjohns** [comment]
I mostly test the build scripts through /build/release.sh and haven't seen that error. But I'm going to pull these in because I think its good clean-up, some of these bugs seem like they've been there for awhile (the validate config) so I'm surprised they went unnoticed this long. We are also running into some webpack issues trying to get Vue 3 working, so my fingers are crossed this might help.

Approved and thanks! I'll make sure you get a shoutout in the next release.

**Pull request merged**
